name: campus_buddy
description: "An app that makes college life easy"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  firebase_core:
  photo_view:
  intl:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  google_sign_in:
  provider:
  flutter_inappwebview:
  flutter_barcode_scanner: ^2.0.0
  firebase_database:
  image_picker: ^1.1.2
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/images/cardimages/
    - assets/images/c3Images/
    - assets/images/gradients/

  uses-material-design: true

  

  
  
