name: campus_buddy
description: "An app that makes college life easy"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  icons_plus: ^5.0.0
  mongo_dart: ^0.10.1
  realm: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
    - assets/images/cardimages/
    - assets/images/c3Images/

  uses-material-design: true

  

  
  
